import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../constants/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.bgSurah,
    },
    mushafPageBorder: {
        flex: 1,
        margin: 8,
        backgroundColor: 'transparent',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(212, 165, 116, 0.1)',
        overflow: 'hidden',
    },
    centerContainer: {
        flex: 1,
        backgroundColor: COLORS.bgSurah,
        alignItems: 'center',
        justifyContent: 'center',
        gap: SIZES.md,
    },
    loadingText: {
        color: COLORS.textSecondary,
        fontSize: SIZES.fontMd,
    },
    errorText: {
        color: COLORS.textSecondary,
        fontSize: SIZES.fontMd,
        textAlign: 'center',
        paddingHorizontal: SIZES.xl,
    },
    retryText: {
        color: COLORS.accent,
        fontSize: SIZES.fontMd,
        fontWeight: '600',
    },
    surahHeader: {
        paddingTop: SIZES.lg,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.bgCard,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    surahHeaderContainer: {
        position: 'relative',
        marginHorizontal: SIZES.lg,
        marginBottom: SIZES.md,
    },
    pageHeaderGradientBorder: {
        borderRadius: SIZES.radiusLg,
        padding: 1,
    },
    pageHeader: {
        borderRadius: SIZES.radiusLg,
        backgroundColor: 'rgba(22, 34, 54, 0.45)',
        padding: SIZES.xl,
        position: 'relative',
        alignItems: 'center',
        overflow: 'hidden',
    },
    headerGlowTop: {
        position: 'absolute',
        top: -60,
        left: 20,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(212, 165, 116, 0.1)',
        shadowColor: COLORS.accent,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 100,
        elevation: 0,
        zIndex: -1,
    },
    glowBgLeft: {
        position: 'absolute',
        bottom: 100,
        left: -150,
        width: 350,
        height: 350,
        borderRadius: 175,
        backgroundColor: 'rgba(45, 106, 79, 0.1)',
        shadowColor: COLORS.primaryLight,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 100,
        zIndex: -1,
    },
    surahNameArabic: {
        fontSize: 40,
        color: COLORS.accent,
        fontFamily: 'Amiri',
        marginBottom: SIZES.lg,
    },
    playButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: SIZES.lg,
        paddingVertical: SIZES.sm + 4,
        borderRadius: SIZES.radiusFull,
        gap: SIZES.sm,
        shadowColor: COLORS.accent,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 8,
    },
    playButtonText: {
        color: COLORS.bgDark,
        fontSize: SIZES.fontSm,
        fontWeight: '700',
    },
    togglesContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(22, 34, 54, 0.5)',
        borderWidth: 1,
        borderColor: 'rgba(212, 165, 116, 0.2)',
        borderRadius: SIZES.radiusFull,
        padding: 4,
        marginBottom: SIZES.xl,
    },
    toggleBtn: {
        paddingHorizontal: SIZES.lg,
        paddingVertical: 8,
        borderRadius: SIZES.radiusFull,
    },
    toggleBtnActive: {
        backgroundColor: COLORS.accent,
    },
    toggleText: {
        fontSize: SIZES.fontSm,
        color: COLORS.textSecondary,
        fontWeight: '600',
    },
    toggleTextActive: {
        color: COLORS.bgDark,
    },
    cornerBox: {
        position: 'absolute',
        width: 24,
        height: 24,
        borderColor: COLORS.dividerGold,
    },
    cbTopLeft: { top: 4, left: 4, borderTopWidth: 2, borderLeftWidth: 2, borderTopLeftRadius: 8 },
    cbTopRight: { top: 4, right: 4, borderTopWidth: 2, borderRightWidth: 2, borderTopRightRadius: 8 },
    cbBottomLeft: { bottom: 4, left: 4, borderBottomWidth: 2, borderLeftWidth: 2, borderBottomLeftRadius: 8 },
    cbBottomRight: { bottom: 4, right: 4, borderBottomWidth: 2, borderRightWidth: 2, borderBottomRightRadius: 8 },
    listContent: {
        paddingBottom: 250,
    },
});
